<?php
/**
 * Created by PhpStorm.
 * User: Alex
 * Date: 2015-10-23
 * Time: 17:05
 */

namespace view;


class AddPubView extends BaseFormView {

    /**
     * action of the form
     * @var string
     */
    private static $action = "?action=admin&add_pub";

    /**
     * ID's for the form elements
     */
    private static $submitPostId = "AddPubView::Submit";
    private static $nameId = "AddPubView::Name";
    private static $addressId = "AddPubView::Address";
    private static $webpageId = "AddPubView::WebpageId";
    private static $messageId = "AddPubView::Message";

    /**
     * Error messages than can be triggered by wrong input
     */
    private static $nameMissingMessage = "Pubens namn saknas, vänligen ange!";
    private static $addressMissingMessage = "Pubens adress saknas, vänligen ange!";
    private static $webpageURLMissingMessage = "Pubens webaddress saknas, vänligen ange!";
    private static $URLWrongFormatMessage = "Pubens webaddress är ej tillåten, måste vara http(s)://www.urlhere.domain";


    /**
     * HTML generated by this form
     *
     * @return string
     */
    public function response() {
        $message = $this->getMessage();
        return "<form method='post' action='". self::$action ."'>
        <p id='" . self::$messageId . "'>" . $message . "</p>" .
        $this->getErrorMessages() .
        $this->getTextField("Namn: ", self::$nameId, self::$inputTypeText) . "<br />" .
        $this->getTextField("Adress: ", self::$addressId, self::$inputTypeText) . "<br />" .
        $this->getTextField("Webbsida: ", self::$webpageId, self::$inputTypeText) . "<br />" .
        "<input type='submit' name='".self::$submitPostId."'>
                </form>";
    }

    /**
     * @return bool
     */
    public function adminPressedSave() {
        return isset($_POST[self::$submitPostId]);
    }

    /**
     * @return \model\Pub|null
     */
    public function getPub() {
        $name = $this->getPostField(self::$nameId);
        $address = $this->getPostField(self::$addressId);
        $webpage = $this->getPostField(self::$webpageId);

        if ($this->isValid($name, $address, $webpage))
            return new \model\Pub($name, $address, $webpage);

        else return null; // controller checks for null
    }

    /**
     * @param $name
     * @param $address
     * @param $webpage
     * @return bool
     */
    private function isValid($name, $address, $webpage) {

        $isValid = true;
        $errorMessages = array();

        if (empty($name)) {
            $isValid = false;
            $errorMessages[] = self::$nameMissingMessage;
        }

        if (empty($address)) {
            $isValid = false;
            $errorMessages[] = self::$addressMissingMessage;
        }

        if (empty($webpage)) {
            $isValid = false;
            $errorMessages[] = self::$webpageURLMissingMessage;

        } elseif (!filter_var($webpage, FILTER_VALIDATE_URL)) {
            $isValid = false;
            $terrorMessages[] = self::$URLWrongFormatMessage;
        }
        $this->setErrorMessages($errorMessages);
        return $isValid;
    }

}